name: Changelog Reminder

on: pull_request
permissions:
  pull-requests: write
jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    if: github.repository == 'raycast/extensions'
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: mskelton/changelog-reminder-action@v3
