name: SizeWatcher
on:
  pull_request_target:
    paths:
      - "extensions/**"
    branches: [main, master]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'raycast/extensions'
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    # ---------- this runs sizewatcher ------------
    - run: npx @adobe/sizewatcher
      env:
        GITHUB_TOKEN: ${{ secrets.RAYCAST_BOT_API_ACCESS_TOKEN }}
